// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbVgni_DwMBca1cc2ZmBmsCu5tD0yzyE',
    appId: '1:483368074672:web:250d3c34ea07a470e76a75',
    messagingSenderId: '483368074672',
    projectId: 'flutter-login-9e946',
    authDomain: 'flutter-login-9e946.firebaseapp.com',
    storageBucket: 'flutter-login-9e946.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVnCY0UlosQJTryO789oGBt0GjOflvz0',
    appId: '1:483368074672:android:7692af67db6dba08e76a75',
    messagingSenderId: '483368074672',
    projectId: 'flutter-login-9e946',
    storageBucket: 'flutter-login-9e946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALFdzqvklGGikrj8gz3Rv8q0v09HEuQ50',
    appId: '1:483368074672:ios:62cdc53a37910182e76a75',
    messagingSenderId: '483368074672',
    projectId: 'flutter-login-9e946',
    storageBucket: 'flutter-login-9e946.appspot.com',
    iosClientId: '483368074672-ep3p57kpqv46revga6g06k8qd3rac75e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPruebaTecnica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALFdzqvklGGikrj8gz3Rv8q0v09HEuQ50',
    appId: '1:483368074672:ios:e59d9edce8f33f4ae76a75',
    messagingSenderId: '483368074672',
    projectId: 'flutter-login-9e946',
    storageBucket: 'flutter-login-9e946.appspot.com',
    iosClientId: '483368074672-t9k8f8gteqgj1o53jvta1iaqbfo9hik6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPruebaTecnica.RunnerTests',
  );
}
